### PR TITLE
support env variables in NumValue

### PR DESCRIPTION
**Pull request by 0xphilipp**
This will add the possibility to access time and block_height variables in NumExpressions.

```rust
        let result = await context.sdk.createJob(context.accountAddress, {
          condition: {
            expr: {
              uint: {
                left: {
                  // access current_time when executing
                  env: 'time',
                },
                op: 'gt',
                right: {
                  ref: 'next_execution'
                }
              }
            },
          },
          recurring: true,
          requeue_on_evict: true,
          vars: [
            {
              static: {
                kind: 'uint',
                name: 'next_execution',
                value: '1',
                update_fn: {
                  on_error: {
                    uint: {
                      expr: {
                        left: {
                          // try again in 1 h
                          simple: 1 * 60 * 60,
                        },
                        op: 'add',
                        right: {
                          // access current time to calculate the next_execution when the execution failed
                          env: 'time',
                        },
                      },
                    },
                  },
                  on_success: {
                    uint: {
                      expr: {
                        left: {
                          // daily
                          simple: 24 * 60 * 60,
                        },
                        op: 'add',
                        right: {
                          // access current time to calculate the next_execution when the execution successful
                          env: 'time',
                        },
                      },
                    },
                  },
                },
              },
            },
          ],
          msgs: [
            {
              wasm: {
                execute: {
                  contract_addr: context.hub,
                  funds: [],
                  msg: base64encode({ harvest: {} }),
                },
              },
            },
          ],
          name: 'eris-harvest',
          reward: '10000',
        });
```

### CODE REVIEW

**Comment by vladjdk** [comment]
Is there any reason why we need to support any data type apart from Uint? Since both timestamp seconds and block heights resolve to u64, it only really makes sense to support that.

**Comment by 0xphilipp** [comment]
comment has been fixed.

**Comment by vladjdk** [comment]
lgtm, thanks for the contribution! //merged

**Comment by 0xphilipp** [comment]
image

Philipp & Vlad 1 : Clippy 0

**Pull request merged**
